In [1]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [2]:
!pip3 install cv2

ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2


In [3]:
!pip3 install opencv-python

In [4]:
import cv2

In [5]:
import numpy as np
import pandas as pd

In [7]:
data = np.array([[   784,  78569],
       [   850, 568956],
       [   400,     56]])

In [20]:
df=pd.DataFrame(data[:,:])

In [21]:
data

array([[   784,  78569],
       [   850, 568956],
       [   400,     56]])

In [24]:
df.agg('sum', axis=1)

0     79353
1    569806
2       456
dtype: int64

In [25]:
df.agg('mean', axis=1)

0     39676.5
1    284903.0
2       228.0
dtype: float64

In [26]:
data[data>500]

array([   784,  78569,    850, 568956])

In [27]:
df[df>500]

0         1
0  784.0   78569.0
1  850.0  568956.0
2    NaN       NaN

In [28]:
np.subtract
np.multiply
np.power
np.divide
np.sin
np.log
np.round
np.ceil
np.abs

AttributeError: 'numpy.ndarray' object has no attribute 'power'

In [29]:
np.power(2,data)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [30]:
data

array([[   784,  78569],
       [   850, 568956],
       [   400,     56]])

In [31]:
np.power(data,2)

array([[    614656, 1878120465],
       [    722500, 1588382736],
       [    160000,       3136]], dtype=int32)

In [32]:
np.sin(data)

array([[-0.98513591, -0.78909012],
       [ 0.98022773,  0.84365997],
       [-0.85091936, -0.521551  ]])

In [33]:
np.cos(data)

array([[ 0.17177673, -0.61427744],
       [-0.19787267,  0.53687788],
       [-0.52529634,  0.85322011]])

In [35]:
np.log(data)

array([[ 6.66440902, 11.2717325 ],
       [ 6.74523635, 13.25155838],
       [ 5.99146455,  4.02535169]])

In [36]:
np.round(data)

array([[   784,  78569],
       [   850, 568956],
       [   400,     56]])

In [37]:
np.ceil(data)

array([[7.84000e+02, 7.85690e+04],
       [8.50000e+02, 5.68956e+05],
       [4.00000e+02, 5.60000e+01]])

In [38]:
np.abs(data)

array([[   784,  78569],
       [   850, 568956],
       [   400,     56]])

In [40]:
np.subtract(data,5000)

array([[ -4216,  73569],
       [ -4150, 563956],
       [ -4600,  -4944]])

In [41]:
np.multiply(data,100)

array([[   78400,  7856900],
       [   85000, 56895600],
       [   40000,     5600]])

In [42]:
np.divide(data,10)

array([[7.84000e+01, 7.85690e+03],
       [8.50000e+01, 5.68956e+04],
       [4.00000e+01, 5.60000e+00]])

In [43]:
data.T

array([[   784,    850,    400],
       [ 78569, 568956,     56]])

In [44]:
np.sqrt(data)

array([[ 28.        , 280.30162326],
       [ 29.15475947, 754.29172076],
       [ 20.        ,   7.48331477]])

In [28]:
import pandas as pd

In [29]:
df=pd.read_csv(r"C:\Users\benja\Downloads\instanceEvent_data.csv",on_bad_lines='skip',chunksize=10000)

In [30]:
df1=pd.read_csv(r"C:\Users\benja\Downloads\instanceUsage_data.csv", chunksize=10000)

In [32]:
df=pd.DataFrame

In [34]:
df1=pd.DataFrame

In [35]:
df.merge(df1,'right')

TypeError: Can only merge Series or DataFrame objects, a <class 'str'> was passed